from __future__ import annotations

from datetime import datetime, timezone

from app.models.schemas import (
    DeviceType,
    HealthState,
    HostInterface,
    HostNode,
    LinkState,
    ProblemSummary,
    TopologyGraph,
    TopologyLink,
)


def build_demo_topology() -> TopologyGraph:
    """Rich demo graph for UI development without a live Zabbix instance."""
    hosts = [
        HostNode(
            hostid="10001",
            name="Core-SW-01",
            host="core-sw-01",
            status=0,
            available=1,
            ip="10.0.0.1",
            device_type=DeviceType.switch,
            health=HealthState.ok,
            groups=["Network / Core"],
            templates=["Generic SNMP Switch"],
            interfaces=[
                HostInterface(interfaceid="1", hostid="10001", ip="10.0.0.1", type=2, main=True, available=1, name="mgmt"),
            ],
            problems=[],
            metrics=[],
            description="Commutateur cœur de réseau",
        ),
        HostNode(
            hostid="10002",
            name="Edge-RTR-01",
            host="edge-rtr-01",
            status=0,
            available=1,
            ip="10.0.0.2",
            device_type=DeviceType.router,
            health=HealthState.warning,
            groups=["Network / Edge"],
            templates=["Generic SNMP Router"],
            interfaces=[
                HostInterface(interfaceid="2", hostid="10002", ip="10.0.0.2", type=2, main=True, available=1),
            ],
            problems=[
                ProblemSummary(eventid="9001", name="ICMP packet loss high", severity=3, clock=int(datetime.now().timestamp())),
            ],
            description="Routeur de bordure",
        ),
        HostNode(
            hostid="10003",
            name="FW-Perimeter",
            host="fw-perimeter",
            status=0,
            available=1,
            ip="10.0.0.3",
            device_type=DeviceType.firewall,
            health=HealthState.ok,
            groups=["Security"],
            templates=["Firewall by SNMP"],
            interfaces=[
                HostInterface(interfaceid="3", hostid="10003", ip="10.0.0.3", type=2, main=True, available=1),
            ],
            problems=[],
            description="Pare-feu périmètre",
        ),
        HostNode(
            hostid="10004",
            name="App-Server-01",
            host="app-server-01",
            status=0,
            available=1,
            ip="10.10.1.10",
            device_type=DeviceType.server,
            health=HealthState.ok,
            groups=["Servers / Application"],
            templates=["Linux by Zabbix agent"],
            interfaces=[
                HostInterface(interfaceid="4", hostid="10004", ip="10.10.1.10", type=1, main=True, available=1),
            ],
            problems=[],
            description="Serveur applicatif",
        ),
        HostNode(
            hostid="10005",
            name="DB-Server-01",
            host="db-server-01",
            status=0,
            available=2,
            ip="10.10.1.20",
            device_type=DeviceType.server,
            health=HealthState.unavailable,
            groups=["Servers / Database"],
            templates=["Linux by Zabbix agent"],
            interfaces=[
                HostInterface(interfaceid="5", hostid="10005", ip="10.10.1.20", type=1, main=True, available=2),
            ],
            problems=[
                ProblemSummary(eventid="9002", name="Zabbix agent unreachable", severity=5, clock=int(datetime.now().timestamp())),
            ],
            description="Serveur base de données",
        ),
        HostNode(
            hostid="10006",
            name="VM-Web-02",
            host="vm-web-02",
            status=0,
            available=1,
            ip="10.10.2.15",
            device_type=DeviceType.vm,
            health=HealthState.ok,
            groups=["Virtualization"],
            templates=["Linux by Zabbix agent"],
            interfaces=[
                HostInterface(interfaceid="6", hostid="10006", ip="10.10.2.15", type=1, main=True, available=1),
            ],
            problems=[],
            description="Machine virtuelle web",
        ),
        HostNode(
            hostid="10007",
            name="Access-SW-Floor2",
            host="access-sw-f2",
            status=0,
            available=1,
            ip="10.0.1.12",
            device_type=DeviceType.switch,
            health=HealthState.ok,
            groups=["Network / Access"],
            templates=["Generic SNMP Switch"],
            interfaces=[
                HostInterface(interfaceid="7", hostid="10007", ip="10.0.1.12", type=2, main=True, available=1),
            ],
            problems=[],
            description="Commutateur d'accès étage 2",
        ),
        HostNode(
            hostid="10008",
            name="Print-Hall-A",
            host="print-hall-a",
            status=0,
            available=1,
            ip="10.10.3.50",
            device_type=DeviceType.printer,
            health=HealthState.ok,
            groups=["Peripherals"],
            templates=["Printer by SNMP"],
            interfaces=[
                HostInterface(interfaceid="8", hostid="10008", ip="10.10.3.50", type=2, main=True, available=1),
            ],
            problems=[],
            description="Imprimante hall A",
        ),
        HostNode(
            hostid="10009",
            name="WS-Admin-04",
            host="ws-admin-04",
            status=0,
            available=1,
            ip="10.10.4.44",
            device_type=DeviceType.workstation,
            health=HealthState.ok,
            groups=["Workstations"],
            templates=["Windows by Zabbix agent"],
            interfaces=[
                HostInterface(interfaceid="9", hostid="10009", ip="10.10.4.44", type=1, main=True, available=1),
            ],
            problems=[],
            description="Poste administrateur",
        ),
        HostNode(
            hostid="10010",
            name="AP-Lobby",
            host="ap-lobby",
            status=0,
            available=1,
            ip="10.0.2.8",
            device_type=DeviceType.network,
            health=HealthState.critical,
            groups=["Network / Wireless"],
            templates=["Wireless AP by SNMP"],
            interfaces=[
                HostInterface(interfaceid="10", hostid="10010", ip="10.0.2.8", type=2, main=True, available=1),
            ],
            problems=[
                ProblemSummary(eventid="9003", name="Radio interface down", severity=4, clock=int(datetime.now().timestamp())),
            ],
            description="Point d'accès hall",
        ),
    ]

    links = [
        TopologyLink(
            id="l1",
            source_hostid="10003",
            target_hostid="10002",
            source_interface="wan0",
            target_interface="eth0",
            link_type="demo",
            evidence="Démo — lien périmètre",
            state=LinkState.normal,
            in_bps=120_000_000,
            out_bps=85_000_000,
            bandwidth_bps=1_000_000_000,
            utilization_pct=12.0,
        ),
        TopologyLink(
            id="l2",
            source_hostid="10002",
            target_hostid="10001",
            link_type="demo",
            evidence="Démo — uplink cœur",
            state=LinkState.high_traffic,
            in_bps=720_000_000,
            out_bps=640_000_000,
            bandwidth_bps=1_000_000_000,
            utilization_pct=72.0,
        ),
        TopologyLink(
            id="l3",
            source_hostid="10001",
            target_hostid="10007",
            link_type="demo",
            evidence="Démo — accès",
            state=LinkState.normal,
            utilization_pct=18.0,
            bandwidth_bps=10_000_000_000,
            in_bps=1_200_000_000,
            out_bps=900_000_000,
        ),
        TopologyLink(
            id="l4",
            source_hostid="10001",
            target_hostid="10004",
            link_type="demo",
            evidence="Démo — serveur app",
            state=LinkState.normal,
            utilization_pct=25.0,
        ),
        TopologyLink(
            id="l5",
            source_hostid="10001",
            target_hostid="10005",
            link_type="demo",
            evidence="Démo — serveur DB",
            state=LinkState.down,
            utilization_pct=None,
        ),
        TopologyLink(
            id="l6",
            source_hostid="10004",
            target_hostid="10006",
            link_type="demo",
            evidence="Démo — VM hébergée",
            state=LinkState.normal,
            utilization_pct=40.0,
        ),
        TopologyLink(
            id="l7",
            source_hostid="10007",
            target_hostid="10008",
            link_type="demo",
            evidence="Démo — imprimante",
            state=LinkState.normal,
            utilization_pct=2.0,
        ),
        TopologyLink(
            id="l8",
            source_hostid="10007",
            target_hostid="10009",
            link_type="demo",
            evidence="Démo — poste",
            state=LinkState.normal,
            utilization_pct=5.0,
        ),
        TopologyLink(
            id="l9",
            source_hostid="10007",
            target_hostid="10010",
            link_type="demo",
            evidence="Démo — Wi-Fi",
            state=LinkState.problem,
            utilization_pct=55.0,
        ),
    ]

    return TopologyGraph(
        hosts=hosts,
        links=links,
        generated_at=datetime.now(timezone.utc).isoformat(),
        zabbix_version="demo",
    )
